# ---------- 霍夫圆检测 ----------
dp: 1.2                # 累积器分辨率比例
minDist: 100.0          # 圆心之间的最小距离
param1: 180.0           # Canny高阈值
param2: 40.0            # 圆检测阈值（越高越严格）
minRadius: 40           # 圆最小半径
maxRadius: 120          # 圆最大半径

# ---------- 霍夫直线检测 ----------
hough_rho: 1.0          # 距离分辨率 (像素)
hough_theta: 1.0        # 角度分辨率 (°)
hough_threshold: 50      # 检测阈值 (累积器最小票数)
minLineLength: 30        # 线段最小长度 (像素)
maxLineGap: 15           # 线段最大间隙 (像素)

# ---------- 角点检测 ----------
use_harris: false        # 是否使用 Harris 角点
maxCorners: 30
qualityLevel: 0.04
minCornerDistance: 15
