# ---------- Circle detection ----------
use_hough_circle: true
dp: 1.2
minDist: 100.0
param1: 180.0
param2: 40.0
minRadius: 40
maxRadius: 120

# ---------- Line detection ----------
hough_rho: 1.0
hough_theta: 1.0
hough_threshold: 50
minLineLength: 30
maxLineGap: 15

# ---------- Corner detection ----------
use_harris: false
maxCorners: 30
qualityLevel: 0.04
minCornerDistance: 15

# ---------- Arc detection ----------
min_arc_points: 60
arc_max_fit_error: 5.0
arc_min_coverage_deg: 70.0
roi_padding_scale: 0.18

# ---------- Soccer pattern priors ----------
short_length_ratio_min: 0.25
short_length_ratio_max: 0.55
long_length_ratio_min: 0.55
long_length_ratio_max: 0.95
thin_thickness_min: 1.0
thin_thickness_max: 3.0
thick_thickness_min: 3.0
thick_thickness_max: 6.0
thickness_search_radius: 8
