# ---------- Circle detection ----------
use_hough_circle: true
dp: 1.2
minDist: 100.0
param1: 180.0
param2: 40.0
minRadius: 40
maxRadius: 120
roi_padding_scale: 0.18
median_blur_kernel_size: 5

# ---------- Corner detection ----------
use_harris: false
maxCorners: 30
qualityLevel: 0.04
minCornerDistance: 15

# ---------- Line detection ----------
hough_rho: 1.0
hough_theta: 1.0
hough_threshold: 50
minLineLength: 30.0
maxLineGap: 15.0
line_hough_threshold_extra: 30.0
line_min_length_extra: 30.0
line_max_gap_scale: 0.5
line_length_min_px: 30.0
line_length_max_radius_ratio: 1.3
line_midpoint_max_radius_ratio: 0.85
line_angle_min_deg: 15.0
line_angle_max_deg: 165.0
line_intensity_diff_min: 30.0

# ---------- ROI edge processing ----------
roi_canny_low_min: 50.0
roi_canny_low_base: 120.0
roi_canny_low_mean_scale: 0.5
roi_canny_high_ratio: 2.5
roi_edge_dilation_iterations: 1

# ---------- Arc detection ----------
min_arc_points: 60
arc_max_fit_error: 5.0
arc_min_coverage_deg: 70.0
arc_blur_kernel_size: 5
arc_canny_low: 60.0
arc_canny_high: 150.0
arc_dilate_iterations: 1
arc_approx_poly_epsilon: 2.0
arc_score_error_weight: 5.0

# ---------- Soccer pattern priors ----------
short_length_ratio_min: 0.25
short_length_ratio_max: 0.55
long_length_ratio_min: 0.55
long_length_ratio_max: 0.95
thin_thickness_min: 1.0
thin_thickness_max: 3.0
thick_thickness_min: 3.0
thick_thickness_max: 6.0
thickness_search_radius: 8

# ---------- Arc debug visualization ----------
arc_visualize_blur: false
arc_visualize_edges: false
arc_visualize_dilated_edges: false
arc_visualize_contours: false
